name: Rancher PushProx CI

on:
  workflow_call:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'

permissions:
  contents: read

jobs:
  build:
    name : Build, test  & validate
    runs-on : ubuntu-latest
    strategy:
      matrix:
          include:
            - platform: linux/amd64
            - platform: linux/arm64
    steps:
      - name : Checkout repository
        uses : actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name : Set up Go
        uses : actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: 1.23
      - name : CI
        run : make ci